function representacion_Spar_time(d, Spar_time, Dmin, Dmax, delta_d, nombre)

    figure('Name', nombre + " NO TG")

    subplot(4,2,1)
    plot(d*1e3,Spar_time(:,1))
    xlabel('Distance (mm)')
    ylabel('Amplitude')
    xlim([Dmin Dmax])
    ylim([min(Spar_time(:,1)) max(Spar_time(:,1))])
    title('ABS(Ifft(S11))')

    subplot(4,2,2)
    plot(Spar_time(:,1))
    xlabel('Sample')
    ylabel('Amplitude')
    xlim([round(Dmin)/(delta_d*1e3)+1 round(Dmax)/(delta_d*1e3)+1])
    ylim([min(Spar_time(:,1)) max(Spar_time(:,1))])
    title('ABS(Ifft(S11))')

    subplot(4,2,3)
    plot(d*1e3,Spar_time(:,3))
    xlabel('Distance (mm)')
    ylabel('Amplitude')
    xlim([Dmin Dmax])
    ylim([min(Spar_time(:,3)) max(Spar_time(:,3))])
    title('ABS(Ifft(S21))')

    subplot(4,2,4)
    plot(Spar_time(:,3))
    % plot(abs(S21_tiempo))
    xlabel('Sample')
    ylabel('Amplitude')
    xlim([round(Dmin)/(delta_d*1e3)+1 round(Dmax)/(delta_d*1e3)+1])
    ylim([min(Spar_time(:,3)) max(Spar_time(:,3))])
    title('ABS(Ifft(S21))')

    subplot(4,2,5)
    plot(d*1e3,Spar_time(:,2))
    xlabel('Distance (mm)')
    ylabel('Amplitude')
    xlim([Dmin Dmax])
    ylim([min(Spar_time(:,2)) max(Spar_time(:,2))])
    title('ABS(Ifft(S12))')

    subplot(4,2,6)
    plot(Spar_time(:,2))
    xlabel('Sample')
    ylabel('Amplitude')
    xlim([round(Dmin)/(delta_d*1e3)+1 round(Dmax)/(delta_d*1e3)+1])
    ylim([min(Spar_time(:,2)) max(Spar_time(:,2))])
    title('ABS(Ifft(S12))')

    subplot(4,2,7)
    plot(d*1e3,Spar_time(:,4))
    % plot(d*1e3,abs(S22_tiempo))
    xlabel('Distance (mm)')
    ylabel('Amplitude')
    xlim([Dmin Dmax])
    ylim([min(Spar_time(:,4)) max(Spar_time(:,4))])
    title('ABS(Ifft(S22))')

    subplot(4,2,8)
    plot(Spar_time(:,4))
    % plot(abs(S22_tiempo))
    xlabel('Sample')
    ylabel('Amplitude')
    xlim([round(Dmin)/(delta_d*1e3)+1 round(Dmax)/(delta_d*1e3)+1])
    ylim([min(Spar_time(:,4)) max(Spar_time(:,4))])
    title('ABS(Ifft(S22))')
    
end